### ISSUE TITLE
Sign in with Discord

### ISSUE THREAD

**Issue by chiKeka** [buildcities/core-product#11]
Review API integration document for ease of implementation.  

- [ ] Authenticate and login user to discord return Oauth payload
- [ ] use auth credentials and check for user membership in build_ guild/server
- [ ] use credentials to check for user membership role in guild
- [ ] return status of user authentication based on steps 1,2 and 3 and return an oauth payload status
- [ ] store payload in UI/UX store
- [ ] test all functions 
- [ ] push and request PR
- [ ] Review implementation
- [ ] merge and publish to staging

**Resources**
- https://www.npmjs.com/package/discord-oauth2
- https://autocode.com/

**Comment by TimJones97** [comment]
1. Sign in with discord
2. Use credentials to check guild membership
3. Use credentials to check for membership role in guild
4. Return auth status/payload
5. Store payload in the UI/UX store library (zustand) 

APIs from autocode
Steps 1,2 & 3 can be implemented and reduced to a single auth function
